spring:
  datasource:
    url: jdbc:postgresql://${SSERAFIMFLOW_POSTGRES_HOST}:${SSERAFIMFLOW_POSTGRES_PORT}/${SSERAFIMFLOW_POSTGRES_DB}?serverTimezone=America/Lima
    username: ${SSERAFIMFLOW_POSTGRES_USER}
    password: ${SSERAFIMFLOW_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 2MB
      max-request-size: 5MB

cloud:
  aws:
    credentials:
      access-key: ${SSERAFIMFLOW_AWS_ACCESS_KEY}
      secret-key: ${SSERAFIMFLOW_AWS_SECRET_KEY}
    region:
      static: ${SSERAFIMFLOW_AWS_REGION}
    stack:
      auto: false

application:
  bucket:
    name: ${SSERAFIMFLOW_S3_BUCKET_NAME}

SSERAFIMFLOW_JWT_SECRET_KEY: ${SSERAFIMFLOW_JWT_SECRET_KEY}
SSERAFIMFLOW_JWT_EXP_TIME: ${SSERAFIMFLOW_JWT_EXP_TIME}

IS_PRODUCTION: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: TRACE

server:
  port: 8080