spring:
  datasource:
    url: jdbc:postgresql://${SSERAFIMFLOW_POSTGRES_HOST}:${SSERAFIMFLOW_POSTGRES_PORT}/${SSERAFIMFLOW_POSTGRES_DB}?serverTimezone=America/Lima
    username: ${SSERAFIMFLOW_POSTGRES_USER}
    password: ${SSERAFIMFLOW_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 2MB
      max-request-size: 5MB

cloudflare:
  r2:
    account:
      id: ${SSERAFIMFLOW_R2_ACCOUNT_ID}
    access:
      key: ${SSERAFIMFLOW_R2_ACCESS_KEY}
    secret:
      key: ${SSERAFIMFLOW_R2_SECRET_KEY}
    bucket:
      name: ${SSERAFIMFLOW_R2_BUCKET_NAME}
    cdn:
      url: ${SSERAFIMFLOW_R2_CDN_URL}

SSERAFIMFLOW_JWT_SECRET_KEY: ${SSERAFIMFLOW_JWT_SECRET_KEY}
SSERAFIMFLOW_JWT_EXP_TIME: ${SSERAFIMFLOW_JWT_EXP_TIME}

IS_PRODUCTION: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: TRACE

server:
  port: 8080